import * as E from './engine.mjs';
export const machines=[{id:'drone',glyph:'✦',color:'#95e6b1',name:'Pip · seedling scout',help:'Click to overcharge: faster harvesting for 8s.'},{id:'moth',glyph:'⋈',color:'#d6b9ff',name:'Luma · prism moth',help:'Click to scatter a chain harvest across nearby nodes.'},{id:'beetle',glyph:'⬡',color:'#f6bc74',name:'Bram · copper digger',help:'Click to crack its target and nearby buried caches.'},{id:'wisp',glyph:'ϟ',color:'#85dcff',name:'Zig · storm sprite',help:'Click to arc electricity between three nodes.'},{id:'rainmaker',glyph:'☂',color:'#78e8d1',name:'Nori · rain frog',help:'Click to ripen a patch into valuable flowers.'},{id:'comet',glyph:'◆',color:'#ffaaa1',name:'Roo · rocket mouse',help:'Click to launch an explosive harvest.'}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function createGarden(s){const seed=(s.runs+1)*7919+s.run.stage*131;return {seed,time:0,toys:[],weather:[],events:{},tuneAt:-20,portalAt:-20,freeze:0,nodes:[],units:[],effects:[],motes:[],hitAt:-10,ability:{pulse:0,storm:0},kills:0,chain:0,chainAt:-5,eventAt:18,bossDone:false,phase:s.run.stage};}
function random(b){b.seed=(Math.imul(1664525,b.seed)+1013904223)>>>0;return b.seed/4294967296;}
export function initialize(s,b){for(let i=0;i<34;i++)spawn(s,b);syncUnits(s,b);if(E.equipped(s,'hatchery'))b.toys.push({kind:'egg',x:500,y:200,hp:3,life:999});}
function spawn(s,b,special){if(b.nodes.length>=65)return;const roll=random(b),kind=special||(roll<.10?'cache':roll<.2?'flower':roll<.30?'amber':'crystal');const hp=kind==='cache'?4:kind==='blight'?3:kind==='boss'?32:1;let x=65+random(b)*870,y=70+random(b)*440;if(kind==='boss'){x=500;y=290;}b.nodes.push({id:random(b),x,y,homeX:x,homeY:y,hp,max:hp,kind,phase:random(b)*6.28,hit:0,respawn:0,ripe:0});}
export function syncUnits(s,b){for(const m of machines){const count=m.id==='drone'?1+Math.min(10,s.run.upgrades.drone):Math.min(5,s.run.upgrades[m.id]||0);while(b.units.filter(x=>x.kind===m.id).length<count)b.units.push({id:random(b),kind:m.id,x:400+random(b)*200,y:260+random(b)*100,angle:random(b)*6.28,target:null,boost:0,cd:0,attack:0});}}
function fx(b,type,x,y,text='',color='#bfffa2',x2=0,y2=0){b.effects.push({type,x,y,text,color,x2,y2,life:type==='text'?1.3:.6,max:type==='text'?1.3:.6});if(b.effects.length>180)b.effects.splice(0,b.effects.length-180);}
function burst(b,x,y,color,count=12){fx(b,'ring',x,y,'',color);for(let i=0;i<count;i++){const a=random(b)*6.28;b.effects.push({type:'spark',x,y,vx:Math.cos(a)*(40+random(b)*150),vy:Math.sin(a)*(40+random(b)*150),life:.5+random(b)*.5,max:1,color});}if(b.effects.length>240)b.effects.splice(0,b.effects.length-240);}
function strike(s,b,node,damage=1,source='auto',multiplier=1){if(!node||node.hp<=0)return;node.hp-=damage;node.hit=.3;fx(b,'ring',node.x,node.y,'',source==='player'?'#edffbe':'#87d9fa');if(node.hp>0)return;
 const rates=E.rates(s),value=(source==='player'?rates.click:rates.idle*.08)*(node.kind==='cache'?5:node.kind==='amber'?2.5:node.kind==='flower'?2:node.kind==='boss'?30:1)*(1+(s.run.upgrades.fortune||0)*.08)*multiplier;
 E.gain(s,value);b.kills++;b.chain=b.time-b.chainAt<1.6?b.chain+1:1;b.chainAt=b.time;burst(b,node.x,node.y,node.kind==='cache'?'#ffcb78':'#a4f4cf');if(source==='player'||node.kind==='cache')fx(b,'text',node.x,node.y,`+${value.toFixed(value<10?1:0)}`,'#ecffd9');
 if(source!=='echo'&&source!=='chain'){const up=s.run.upgrades;if((E.equipped(s,'gardener')&&source==='auto'&&b.kills%5===0)||(up.bloom>=3&&b.kills%6===0))spawn(s,b,'flower');if(E.equipped(s,'fungi')&&b.kills%8===0&&b.toys.length<8)b.toys.push({kind:'mushroom',x:node.x,y:node.y,life:12});if(node.kind==='flower'&&(E.equipped(s,'domino')||up.bloom>=6))nearby(s,b,node,3,100,'chain');if(node.kind==='cache'){if(up.lens>=6||(up.fortune>=3&&(s.run.excavated||0)%5===0))for(let i=0;i<3;i++)spawn(s,b,'flower');if(up.pick>=3)nearby(s,b,node,3,120,'chain');}if(node.lit>0)nearby(s,b,node,2,150,'chain');}
 if(node.kind==='boss'){b.bossDone=true;s.run.guardian=true;fx(b,'text',500,200,'HEART UNBOUND','#ffdb92');}
 if(node.kind==='cache'){s.run.excavated=(s.run.excavated||0)+1;if((s.run.excavated%5)===0){s.run.finds=(s.run.finds||0)+1;fx(b,'text',node.x,node.y-32,'ANCIENT MEMORY +1 SEED','#edc9ff');}}
 node.respawn=1.6;node.hp=0;
 if((source==='player'||(source==='auto'&&s.run.upgrades.echo>=3))&&(s.run.upgrades.echo||0)>0){const other=b.nodes.find(q=>q!==node&&q.hp>0&&Math.hypot(q.x-node.x,q.y-node.y)<170);if(other){fx(b,'beam',node.x,node.y,'','#e5b6ff',other.x,other.y);strike(s,b,other,1+(s.run.upgrades.echo||0)*.1,'echo',.6);if(s.run.upgrades.echo>=6)nearby(s,b,other,1,180,'chain');}}
}
export function interact(s,b,x,y){if(!s.run||s.run.draft||s.run.finished||b.time-b.hitAt<.16)return false;b.hitAt=b.time;
 const toy=b.toys.find(q=>Math.hypot(q.x-x,q.y-y)<32);if(toy){if(toy.kind==='egg'&&--toy.hp>0){burst(b,x,y,'#fff0b0');return true;}toy.life=0;if(toy.kind==='egg'){b.units.push({id:random(b),kind:'drone',x,y,target:null,angle:0,boost:8,cd:0,attack:0,baby:true});fx(b,'text',x,y,'HELLO, LITTLE ONE!');}else if(toy.kind==='lantern')spawn(s,b,'cache');else{for(const u of b.units)u.boost=8;nearby(s,b,toy,7,500,'player');}burst(b,x,y,'#ffdf8b',20);return true;}
 const unit=b.units.find(u=>Math.hypot(u.x-x,u.y-y)<26&&u.cd<=0);if(unit){unit.cd=4;unit.boost=8;burst(b,unit.x,unit.y,'#f0c9ff',20);fx(b,'text',unit.x,unit.y-24,'OVERCHARGED','#edc9ff');const up=s.run.upgrades;
 if(up.tempo>=3)for(const k of ['pulse','storm'])b.ability[k]=Math.max(0,b.ability[k]-1);
 if(E.equipped(s,'duet')||up.harmony>=3){const buddy=b.units.filter(u=>u!==unit).sort((a,c)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(c.x-x,c.y-y))[0];if(buddy){buddy.boost=8;fx(b,'beam',x,y,'','#ffe0a2',buddy.x,buddy.y);nearby(s,b,buddy,1,300,'chain');}}
 if(up.magnet>=3)for(const q of b.nodes)if(Math.hypot(q.x-x,q.y-y)<220){q.x+=(x-q.x)*.4;q.y+=(y-q.y)*.4;}
 if(unit.kind==='drone'&&up.drone>=6)for(const u of b.units)u.boost=8;
 if(unit.kind==='comet'&&up.comet>=6)b.weather.push({x:0,y,life:3});
 const near=b.nodes.filter(n=>n.hp>0).sort((a,c)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(c.x-x,c.y-y));const count=unit.kind==='comet'?7:unit.kind==='moth'?(up.moth>=6?9:5):unit.kind==='wisp'?(up.wisp>=6?7:3):unit.kind==='beetle'?(up.beetle>=6?8:2):unit.kind==='rainmaker'?(up.rainmaker>=6?7:1):1;for(const q of near.slice(0,count)){if(unit.kind==='rainmaker'){if(q.kind==='boss')continue;q.kind='flower';q.ripe=12;}else strike(s,b,q,unit.kind==='beetle'?4:1,'player',.75);}return true;}
 const node=b.nodes.filter(q=>q.hp>0).sort((a,c)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(c.x-x,c.y-y))[0];if(!node||Math.hypot(node.x-x,node.y-y)>48)return false;const amount=E.click(s);if(!amount)return false;const up=s.run.upgrades;
 if((E.equipped(s,'ricochet')||up.touch>=3)&&s.run.combo>0&&s.run.combo%3===0)nearby(s,b,node,E.equipped(s,'ricochet')?3:1,900,'chain');
 if(s.run.combo===10&&b.time-b.tuneAt>12){b.tuneAt=b.time;if(E.equipped(s,'drum')){for(const u of b.units)u.boost=8;fx(b,'text',500,130,'EVERYBODY, DANCE!');}if(up.touch>=6)nearby(s,b,node,5,180,'chain');if(up.tempo>=6)for(const k of ['pulse','storm'])b.ability[k]=Math.max(0,b.ability[k]-3);}
 if(E.equipped(s,'portal')&&b.time-b.portalAt>6){b.portalAt=b.time;if(b.portal){for(const u of b.units){u.x=x;u.y=y;}fx(b,'beam',b.portal.x,b.portal.y,'','#d6baff',x,y);b.portal=null;}else b.portal={x,y};}
 const critical=random(b)<.08+(s.run.upgrades.fortune||0)*.025;strike(s,b,node,critical?4:up.pick>=6&&node.kind==='cache'?4:1+(s.run.upgrades.pick||0)*.3,'player',critical?2:1);if(critical&&up.fortune>=6)nearby(s,b,node,3,180,'chain');if(critical)fx(b,'text',x,y-28,'BLOOM! ×2','#ffcd8c');
 const arcs=(s.run.upgrades.wisp||0)>0||s.run.relics.includes('thunder');if(arcs){const near=b.nodes.find(q=>q!==node&&q.hp>0&&Math.hypot(q.x-x,q.y-y)<150);if(near){fx(b,'beam',x,y,'','#8adfff',near.x,near.y);strike(s,b,near,.6,'chain');}}
 if((s.run.upgrades.magnet||0)>0)for(const q of b.nodes)if(q.hp>0&&q!==node&&Math.hypot(q.x-x,q.y-y)<200){q.x+=(x-q.x)*Math.min(.4,.08+s.run.upgrades.magnet*.015);q.y+=(y-q.y)*Math.min(.4,.08+s.run.upgrades.magnet*.015);}
 return true;
}
export function ability(s,b,kind){if(!s.run||s.run.draft||s.run.finished||!['pulse','storm'].includes(kind)||b.ability[kind]>0)return false;if(kind==='pulse'&&E.equipped(s,'snow'))b.freeze=3;
 if(kind==='pulse'&&s.run.upgrades.magnet>=6)spiral(b);
 if(kind==='storm'&&E.equipped(s,'encore'))for(const u of b.units){u.boost=8;nearby(s,b,u,1,1000,'chain');}
 const cooldown=kind==='pulse'?16:28;b.ability[kind]=cooldown/(1+(s.run.upgrades.tempo||0)*.1);fx(b,'wave',500,280,'',kind==='pulse'?'#a5f5df':'#d2b1ff');for(const q of b.nodes.filter(q=>q.hp>0)){if(kind==='storm')q.kind=q.kind==='boss'?'boss':'flower';strike(s,b,q,kind==='pulse'?1.5:1,'ability',.65);}return true;}
export function step(s,b,dt){if(!s.run||s.run.draft||s.run.finished)return;dt=clamp(dt,0,.2);b.time+=dt;E.tick(s,dt);syncUnits(s,b);
 if(b.freeze>0){b.freeze-=dt;if(b.freeze<=0)for(const q of [...b.nodes])strike(s,b,q,1,'chain',.2);}
 function every(id,seconds,fn){if(E.equipped(s,id)&&b.time>=(b.events[id]??seconds)){b.events[id]=b.time+seconds;fn();}}
 every('picnic',18,()=>{for(const u of b.units){u.x=450+random(b)*100;u.y=260+random(b)*60;u.boost=8;}fx(b,'text',500,200,'PICNIC CLUB!');});
 every('tide',15,()=>spiral(b));every('meteor',20,()=>b.weather.push({x:0,y:120+random(b)*300,life:3}));
 every('lantern',12,()=>{if(b.toys.length<8)b.toys.push({kind:'lantern',x:120+random(b)*760,y:130+random(b)*300,life:10});});
 every('firefly',14,()=>{for(const q of b.nodes.filter(q=>q.hp>0).slice(0,10)){q.lit=8;fx(b,'ring',q.x,q.y,'','#fff4a0');}});
 for(const toy of b.toys){toy.life-=dt;if(toy.kind==='lantern')toy.x+=Math.sin(b.time)*dt*24;}b.toys=b.toys.filter(q=>q.life>0);
 for(const meteor of b.weather){meteor.life-=dt;meteor.x+=400*dt;for(const q of b.nodes)if(q.hp>0&&Math.hypot(q.x-meteor.x,q.y-meteor.y)<55)strike(s,b,q,4,'chain',.4);}b.weather=b.weather.filter(q=>q.life>0);
 for(const k of Object.keys(b.ability))b.ability[k]=Math.max(0,b.ability[k]-dt);for(const q of b.nodes){q.hit=Math.max(0,q.hit-dt);q.lit=Math.max(0,(q.lit||0)-dt);q.ripe=Math.max(0,q.ripe-dt);if(q.hp<=0)q.respawn-=dt;else if(b.freeze<=0){q.x+=(q.homeX+Math.sin(b.time*.4+q.phase)*9-q.x)*dt*.7;q.y+=(q.homeY+Math.cos(b.time*.35+q.phase)*7-q.y)*dt*.7;}}
 b.nodes=b.nodes.filter(q=>q.hp>0||q.respawn>0);while(b.nodes.length<34+Math.min(18,(s.run.upgrades.bloom||0)*3))spawn(s,b);
 if(b.phase===4&&!b.bossDone&&!s.run.guardian&&!b.nodes.some(q=>q.kind==='boss'))spawn(s,b,'boss');
 if(b.time>b.eventAt){b.eventAt=b.time+(s.run.upgrades.lens>=3?12:18);spawn(s,b,'cache');fx(b,'text',500,52,'A MEMORY SURFACES','#dfc5ff');burst(b,500,70,'#cbb4ff',20);}
 for(const u of b.units){u.boost=Math.max(0,u.boost-dt);u.cd=Math.max(0,u.cd-dt);u.attack=Math.max(0,(u.attack||0)-dt);let target=b.nodes.find(n=>n.id===u.target&&n.hp>0);if(!target){let alive=b.nodes.filter(q=>q.hp>0);if((E.equipped(s,'courier')||s.run.upgrades.beetle>=3&&u.kind==='beetle'||s.run.upgrades.drone>=3&&u.kind==='drone')&&alive.some(q=>q.kind==='cache'))alive=alive.filter(q=>q.kind==='cache');target=alive[Math.floor(random(b)*alive.length)];u.target=target?.id;}if(!target)continue;const dx=target.x-u.x,dy=target.y-u.y,d=Math.hypot(dx,dy),speed=(u.boost>0?145:75)*(1+(s.run.upgrades.coil||0)*.025);u.angle=Math.atan2(dy,dx);u.x+=dx/Math.max(1,d)*Math.min(d,speed*dt);u.y+=dy/Math.max(1,d)*Math.min(d,speed*dt);if(s.run.upgrades.coil>=6&&u.boost>0&&u.attack<=0){nearby(s,b,u,1,38,'chain');u.attack=.4;}if(d<18&&u.attack<=0){u.attack=.4;strike(s,b,target,(u.kind==='beetle'?(s.run.upgrades.beetle>=3?4:2):1)*(1+(s.run.upgrades[u.kind]||0)*.06),'auto',1/Math.sqrt(Math.max(1,b.units.length)));if(u.kind==='moth'&&s.run.upgrades.moth>=3)nearby(s,b,target,2,160,'chain');
 if(u.kind==='rainmaker'&&s.run.upgrades.rainmaker>=3){const flower=b.nodes.find(q=>q.hp>0&&q.kind!=='boss');if(flower)flower.kind='flower';}
 if(u.kind==='comet'&&s.run.upgrades.comet>=3||s.run.upgrades.harmony>=6&&u.boost>0)nearby(s,b,target,3,100,'chain');
 if(s.run.upgrades.coil>=3){const buddy=b.units.find(q=>q!==u&&q.target);const q=b.nodes.find(q=>q.id===buddy?.target&&q.hp>0);if(q){fx(b,'beam',u.x,u.y,'','#abeacc',q.x,q.y);strike(s,b,q,.3,'chain',.15);}}
 if(u.kind==='wisp'&&s.run.upgrades.wisp>=3)nearby(s,b,target,1,160,'chain');
 if(u.kind==='wisp'){const q=b.nodes.find(q=>q.hp>0&&q!==target&&Math.hypot(q.x-target.x,q.y-target.y)<140);if(q){fx(b,'beam',u.x,u.y,'','#8ce1ff',q.x,q.y);strike(s,b,q,.5,'auto',.3);}}u.target=null;}}
 for(const f of b.effects){f.life-=dt;if(f.type==='spark'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=50*dt;}if(f.type==='text')f.y-=24*dt;}b.effects=b.effects.filter(f=>f.life>0);if(b.time-b.chainAt>1.6)b.chain=0;
}


function nearby(s,b,point,count,radius,source='chain'){const targets=b.nodes.filter(q=>q.hp>0&&q!==point&&Math.hypot(q.x-point.x,q.y-point.y)<radius).sort((a,c)=>Math.hypot(a.x-point.x,a.y-point.y)-Math.hypot(c.x-point.x,c.y-point.y)).slice(0,count);for(const q of targets){fx(b,'beam',point.x,point.y,'','#f3d1ff',q.x,q.y);strike(s,b,q,1,source,.35);}}
function spiral(b){b.nodes.forEach((q,i)=>{if(q.hp<=0||q.kind==='boss')return;const a=i*2.4,r=60+Math.sqrt(i)*28;q.x=500+Math.cos(a)*r;q.y=290+Math.sin(a)*r*.7;});fx(b,'wave',500,290,'','#aadfff');}
