// Original generative score: five modal environments, slow pads, drifting bells and stereo echoes.
export class Atmosphere{
 constructor(){this.ctx=null;this.enabled=true;this.volume=.3;this.stage=0;this.beat=0;this.next=0;this.voices=new Set();}
 async start(){if(!this.ctx){const c=this.ctx=new AudioContext();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.reverb=c.createConvolver();const ir=c.createBuffer(2,c.sampleRate*3,c.sampleRate);for(let ch=0;ch<2;ch++){const a=ir.getChannelData(ch);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,3)*.3;}this.reverb.buffer=ir;this.reverb.connect(this.master);this.timer=setInterval(()=>this.schedule(),200);}await this.ctx.resume();this.set(this.enabled,this.volume,this.stage);}
 set(enabled,volume,stage=0){this.enabled=enabled;this.volume=volume;this.stage=stage;if(this.ctx)this.master.gain.setTargetAtTime(enabled?volume*.45:0,this.ctx.currentTime,1);}
 note(midi,t,duration,gain=.1,type='sine',pan=0){const c=this.ctx,o=c.createOscillator(),a=c.createGain(),p=c.createStereoPanner();o.type=type;o.frequency.value=440*Math.pow(2,(midi-69)/12);p.pan.value=pan;a.gain.setValueAtTime(0,t);a.gain.linearRampToValueAtTime(gain,t+.5);a.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(a);a.connect(p);p.connect(this.master);p.connect(this.reverb);o.start(t);o.stop(t+duration+.1);}
 schedule(){if(!this.ctx||this.ctx.state!=='running')return;const now=this.ctx.currentTime;if(now<this.next)return;this.next=now+1.7;const roots=[50,48,53,45,50],root=roots[this.stage%5],scale=[0,2,5,7,9,12,14];if(this.beat%4===0){const chord=[0,7,12,16][Math.floor(this.beat/16)%4];for(const v of [0,7,12])this.note(root-12+v+(chord===16?5:chord),now,9,.07,'sine',(v-6)/12);}const index=[0,3,2,5,1,4,6,3][this.beat%8];this.note(root+12+scale[index],now,3,.045,'sine',Math.sin(this.beat)*.65);if(this.stage>=2&&this.beat%2===0)this.note(root+24+scale[(index+2)%7],now+.6,2,.018);this.beat++;}
 effect(kind='hit'){if(!this.ctx||!this.sfxEnabled)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.frequency.value=440*Math.pow(2,((kind==='burst'?86:74+this.beat%5)-69)/12);o.connect(g);g.connect(c.destination);g.gain.setValueAtTime((this.sfxVolume||0)*.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.35);o.start();o.stop(c.currentTime+.4);}
}
