import test from 'node:test';import assert from 'node:assert/strict';import * as E from './engine.mjs';import * as G from './garden.mjs';
const game=style=>{const s=E.start(E.fresh('Test',style));const b=G.createGarden(s);G.initialize(s,b);return {s,b};};
test('version 1 saves migrate without losing currency or permanent progress',()=>{const old={schema:1,name:'Old grove',style:'keeper',seeds:73,runs:4,tree:{'hand-0':2},history:[],totalClicks:12,updated:1,run:{energy:40,earned:80,elapsed:4,stage:0,upgrades:{touch:2,drone:1,coil:0,lens:0},relics:[],draft:null,combo:0,lastClick:0,finished:false}};E.validate(old);assert.equal(old.schema,3);assert.equal(old.seeds,82);assert.deepEqual(old.tree,{});E.validate(old);assert.equal(old.seeds,82);assert.equal(old.run.upgrades.moth,0);assert.equal(old.run.energy,40);});
test('all 16 blueprints have finite costs and purchase effects',()=>{const {s,b}=game('warden');s.run.energy=1e8;for(const g of E.gear){assert.ok(Number.isFinite(E.price(s,g.id)));assert.ok(E.buy(s,g.id));assert.equal(s.run.upgrades[g.id],1);}G.syncUnits(s,b);assert.equal(E.gear.length,16);for(const m of G.machines)assert.ok(b.units.some(u=>u.kind===m.id));});
test('helpers traverse the board and break nodes',()=>{const {s,b}=game('weaver');const x=b.units[0].x;for(let i=0;i<100;i++)G.step(s,b,.1);assert.notEqual(b.units[0].x,x);assert.ok(b.kills>0);assert.ok(s.run.energy>24);});
test('clicking a helper triggers boost and cooldown',()=>{const {s,b}=game('warden'),u=b.units[0];G.interact(s,b,u.x,u.y);assert.equal(u.boost,8);assert.equal(u.cd,4);});
test('caches take damage, award discoveries and produce finite rewards',()=>{const {s,b}=game('keeper');s.run.upgrades.pick=12;const q=b.nodes.find(q=>q.kind==='cache');assert.ok(q);b.units=[];for(let i=0;i<5;i++){q.hp=1;q.kind='cache';b.time+=1;E.tick(s,1);G.interact(s,b,q.x,q.y);}assert.equal(s.run.finds,1);assert.ok(Number.isFinite(s.run.energy));});
test('abilities obey cooldown and drafts pause the garden',()=>{const {s,b}=game('warden');assert.ok(G.ability(s,b,'pulse'));assert.equal(G.ability(s,b,'pulse'),false);s.run.draft=['sap','moth','rain'];const before=s.run.earned;G.step(s,b,.1);assert.equal(s.run.earned,before);assert.equal(G.ability(s,b,'storm'),false);});
test('garden effects and entities remain bounded under sustained play',()=>{const {s,b}=game('warden');for(const g of E.gear)s.run.upgrades[g.id]=6;for(let i=0;i<4000;i++){G.step(s,b,.1);if(i%10===0)G.ability(s,b,'pulse');}assert.ok(b.nodes.length<=65);assert.ok(b.units.length<=36);assert.ok(b.effects.length<=260);E.validate(s);});
test('prestige preserves skills and pays only once',()=>{const {s}=game('weaver');s.tree['ricochet']=1;s.run.earned=E.target(s);const amount=E.reward(s);assert.equal(E.prestige(s),amount);assert.equal(E.prestige(s),false);assert.equal(s.tree['ricochet'],1);});
test('reject corrupt and future save formats',()=>{const {s}=game('keeper');assert.throws(()=>E.validate({...s,schema:99}));assert.throws(()=>E.validate({...s,seeds:-1}));assert.throws(()=>E.validate({...s,run:{...s.run,finds:Infinity}}));});
function simulate(style){let {s,b}=game(style);const cadence=style==='keeper'?.5:style==='warden'?1.5:Infinity;let last=-10;const order=style==='keeper'?['touch','coil','lens','pick','echo','wisp','fortune']:style==='weaver'?['drone','coil','lens','harmony','moth','beetle']:['drone','touch','coil','lens','wisp','moth','harmony'];for(let t=0;t<1000;t+=.1){G.step(s,b,.1);if(t-last>=cadence){last=t;const q=b.nodes.find(q=>q.hp>0);if(q)G.interact(s,b,q.x,q.y);}if(style!=='weaver'){G.ability(s,b,'pulse');G.ability(s,b,'storm');}let selected=order.filter(id=>s.run.upgrades[id]<6).map(id=>({id,cost:E.price(s,id)})).sort((a,b)=>a.cost-b.cost)[0];if(selected&&selected.cost<=s.run.energy)E.buy(s,selected.id);if(s.run.earned>=E.target(s)){if(s.run.stage===4&&!s.run.guardian)continue;E.advance(s,()=>.2);if(s.run.finished)return Math.round(s.run.elapsed);E.choose(s,s.run.draft[0]);b=G.createGarden(s);G.initialize(s,b);}}return 1000;}
test('starter expeditions are shorter for all three playstyles',()=>{const values=Object.keys(E.styles).map(style=>({style,seconds:simulate(style)}));console.log('Living board balance:',JSON.stringify(values));assert.ok(values.every(x=>x.seconds>90&&x.seconds<480));assert.ok(Math.max(...values.map(x=>x.seconds))/Math.min(...values.map(x=>x.seconds))<1.8);});

test('three keepsakes maximum and choices cannot change in a run',()=>{const s=E.fresh();s.seeds=1000;for(const q of E.nodes)assert.ok(E.unlock(s,q.id));for(const q of E.nodes.slice(0,3))assert.ok(E.equip(s,q.id));assert.equal(E.equip(s,E.nodes[3].id),false);E.start(s);assert.equal(E.equip(s,E.nodes[0].id),false);assert.equal(E.unlock(s,E.nodes[0].id),false);E.validate(s);});
test('full restoration gives one permanent discovery with no double claim',()=>{const {s}=game('warden');s.run.stage=4;s.run.earned=E.target(s);assert.equal(E.advance(s),false);s.run.guardian=true;assert.ok(E.advance(s));E.prestige(s);assert.equal(s.offers.length,3);const id=s.offers[0];assert.ok(E.claim(s,id));assert.equal(E.claim(s,id),false);assert.ok(s.tree[id]);assert.ok(s.loadout.includes(id));});
test('workshop evolutions cap at six and stop spending',()=>{const {s}=game('warden');s.run.energy=1e8;for(const q of E.gear){for(let i=0;i<6;i++)assert.ok(E.buy(s,q.id));const before=s.run.energy;assert.equal(E.buy(s,q.id),false);assert.equal(before,s.run.energy);}assert.equal(E.buy(s,'invalid'),false);E.validate(s);});
test('egg hatches a character and storm cannot destroy guardian identity',()=>{const s=E.fresh();s.tree.hatchery=1;s.loadout=['hatchery'];E.start(s);const b=G.createGarden(s);G.initialize(s,b);assert.equal(b.toys[0].kind,'egg');const egg=b.toys[0];for(let i=0;i<3;i++){b.time+=1;G.interact(s,b,egg.x,egg.y);}assert.ok(b.units.some(u=>u.baby));s.run.stage=4;const c=G.createGarden(s);G.initialize(s,c);G.step(s,c,.1);G.ability(s,c,'storm');assert.ok(c.nodes.some(q=>q.kind==='boss'));});
test('passive economy is stable across simulation frequencies',()=>{function sim(hz){const {s,b}=game('weaver');s.run.upgrades.drone=3;for(let i=0;i<hz*30;i++)G.step(s,b,1/hz);return s.run.earned;}const low=sim(30),high=sim(240);assert.ok(Math.abs(low-high)/high<.04,low+' vs '+high);});
test('every keepsake survives sustained simulation and serialization',()=>{for(const keep of E.nodes){const s=E.fresh();s.tree[keep.id]=1;s.loadout=[keep.id];E.start(s);const b=G.createGarden(s);G.initialize(s,b);for(const g of E.gear)s.run.upgrades[g.id]=6;for(let i=0;i<1200;i++){G.step(s,b,.05);if(i%20===0){G.ability(s,b,'pulse');G.ability(s,b,'storm');const q=b.nodes.find(n=>n.hp>0);if(q)G.interact(s,b,q.x,q.y);}}assert.ok(b.toys.length<10);assert.ok(b.effects.length<=260);E.validate(JSON.parse(JSON.stringify(s)));}});
