import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from './engine.mjs';
test('new groves are isolated',()=>{const a=E.start(E.fresh()),b=E.start(E.fresh());E.tick(a,10);assert.equal(b.run.energy,0);assert.ok(a.run.energy>0);});
test('spending does not reduce restoration progress; insufficient purchases fail',()=>{const s=E.start(E.fresh());assert.equal(E.buy(s,'drone'),false);E.tick(s,100);const before=s.run.earned;assert.equal(E.buy(s,'drone'),true);assert.equal(s.run.earned,before);assert.ok(s.run.energy<before);});
test('rhythm bonus and click rate limit work',()=>{const s=E.start(E.fresh());assert.ok(E.click(s)>0);assert.equal(E.click(s),0);E.tick(s,.5);E.click(s);assert.equal(s.run.combo,1);E.tick(s,2);assert.equal(s.run.combo,0);});
test('districts require progress, drafts pause and reject unoffered relics',()=>{const s=E.start(E.fresh());assert.equal(E.advance(s),false);E.gain(s,E.target(s));assert.equal(E.advance(s,()=>0),true);const before=s.run.earned;E.tick(s,100);assert.equal(before,s.run.earned);assert.equal(E.choose(s,'bad'),false);assert.equal(E.choose(s,s.run.draft[0]),true);});
test('completion and prestige bank seeds once, preserve tree and reset run',()=>{const s=E.start(E.fresh());s.tree['hand-0']=1;for(let i=0;i<5;i++){E.gain(s,E.target(s));E.advance(s,()=>0);if(s.run.draft)E.choose(s,s.run.draft[0]);}assert.ok(s.run.finished);assert.ok(E.reward(s)>=42);const reward=E.prestige(s);assert.equal(s.seeds,reward);assert.equal(s.run,null);assert.equal(s.tree['hand-0'],1);assert.equal(E.prestige(s),false);});
test('tree enforces prerequisites, rank caps, spending and expedition lock',()=>{const s=E.fresh();s.seeds=1000;assert.equal(E.unlock(s,'hand-1'),false);for(let i=0;i<3;i++)assert.ok(E.unlock(s,'hand-0'));assert.equal(E.unlock(s,'hand-0'),false);assert.ok(E.unlock(s,'hand-1'));E.start(s);assert.equal(E.unlock(s,'machine-0'),false);});
test('save roundtrip and corrupt/future data rejection',()=>{const s=E.start(E.fresh());E.tick(s,30);assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);assert.throws(()=>E.validate({...s,schema:2}));assert.throws(()=>E.validate({...s,seeds:-1}));assert.throws(()=>E.validate({...s,tree:{bad:999}}));assert.throws(()=>E.validate({...s,run:{...s.run,stage:9}}));});
test('offline gain is capped and cannot cross draft decisions automatically',()=>{const s=E.start(E.fresh());E.tick(s,999999);assert.equal(s.run.elapsed,28800);assert.equal(s.run.stage,0);E.advance(s);const before=s.run.earned;E.tick(s,300);assert.equal(s.run.earned,before);});
export function simulate(style,runCount=0,tree={}){const s=E.fresh('Simulation',style);s.runs=runCount;s.tree={...tree};E.start(s);let clickClock=0;for(let t=0;t<3600;t+=.25){E.tick(s,.25);clickClock+=.25;if(style!=='weaver'&&clickClock>=(style==='keeper'?.5:1.5)){E.click(s);clickClock=0;}const candidates=E.gear.filter(g=>g.id==='coil'||g.id==='lens'||(g.id==='touch'&&style!=='weaver')||(g.id==='drone'&&style!=='keeper'));let best=null,bestRatio=0;for(const g of candidates){const cost=E.price(s,g.id);const before=E.rates(s);const cps=style==='keeper'?2*1.30:style==='warden'?2/3:0;const prod=(before.idle+before.click*cps)*(1+s.run.upgrades.lens*.12);s.run.upgrades[g.id]++;const after=E.rates(s);const prod2=(after.idle+after.click*cps)*(1+s.run.upgrades.lens*.12);s.run.upgrades[g.id]--;const ratio=(prod2-prod)/cost;if(ratio>bestRatio){best=g;bestRatio=ratio;}}if(best&&s.run.energy>=E.price(s,best.id))E.buy(s,best.id);if(s.run.earned>=E.target(s)){E.advance(s,()=>.2);if(s.run.draft){const id=s.run.draft.includes(style==='keeper'?'sap':style==='weaver'?'moth':'rain')?(style==='keeper'?'sap':style==='weaver'?'moth':'rain'):s.run.draft[0];E.choose(s,id);}if(s.run.finished)return {style,seconds:s.run.elapsed,seeds:E.reward(s)};}}throw Error('Run exceeded one hour');}
test('representative active, automated and hybrid builds finish within a comparable window',()=>{const results=Object.keys(E.styles).map(x=>simulate(x));console.log('Balance sample:',JSON.stringify(results));const times=results.map(r=>r.seconds);assert.ok(Math.max(...times)/Math.min(...times)<1.5,'Playstyles diverged more than 50%');assert.ok(times.every(t=>t>=360&&t<=1200),'Runs should last 6–20 minutes in this simulation');});
